[theme]
base            = "dark"
primaryColor    = "#c026d3"
backgroundColor = "#0a041a"
secondaryBackgroundColor = "#10052a"
textColor       = "#f0e6ff"
font            = "sans serif"

[server]
headless      = true
port          = 8501
enableCORS    = false

[browser]
gatherUsageStats = false
